---
device: 'cpu'
seed: 0
sensor: 'GuardianRT'
pump: 'Insulet'

env_type: 'train'
obs_type: 'current'

start_midnight: True # If true simu starts at midnight, if False a random time in the day.
use_start_time: False # overwrites the above. This is useful in testing.
start_time: 0 # custom start time given in minute of the day . <int> expected

use_individual_meal_protocol: False  # True or False
meal_protocol:  # Global Meal Scenario, applicable when individuals meals are not assigned.
  probability: [0.95, 0.3, 0.95, 0.3, 0.95, 0.3]  # [0,1], can meal
  amount_mu: [45, 10, 70, 10, 80, 10]  # meal mu, sigma in grams.
  amount_sigma: [10, 5, 10, 5, 10, 5]
  time_lower_bound: [5, 9, 10, 14, 16, 20]  # times are in 24-hour format
  time_upper_bound: [9, 10, 14, 16, 20, 23]
  time_mu: [7, 9.5, 12, 15, 18, 21.5]
  time_sigma: [60, 30, 60, 30, 60, 30] # minutes

# list the patient names here:
patients:
  patient1:
    name: 'adolescent#001'
    n_env: 2
    meal_protocol:
      probability: [ 0.95, 0.3, 0.95, 0.3, 0.95, 0.3 ]
      amount_mu: [ 45, 10, 70, 10, 80, 10 ]
      amount_sigma: [ 10, 5, 10, 5, 10, 5 ]
      time_lower_bound: [ 5, 9, 10, 14, 16, 20 ]
      time_upper_bound: [ 9, 10, 14, 16, 20, 23 ]
      time_mu: [ 7, 9.5, 12, 15, 18, 21.5 ]
      time_sigma: [ 60, 30, 60, 30, 60, 30 ]
  patient2:
    name: 'adolescent#002'
    n_env: 1
    meal_protocol:
      probability: [ 0.95, 0.3, 0.95, 0.3, 0.95, 0.3 ]
      amount_mu: [ 45, 10, 70, 10, 80, 10 ]
      amount_sigma: [ 10, 5, 10, 5, 10, 5 ]
      time_lower_bound: [ 5, 9, 10, 14, 16, 20 ]
      time_upper_bound: [ 9, 10, 14, 16, 20, 23 ]
      time_mu: [ 7, 9.5, 12, 15, 18, 21.5 ]
      time_sigma: [ 60, 30, 60, 30, 60, 30 ]
