[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "glucoenv"
authors = [{name = "Chirath", email = "chirathyh@gmail.com"}]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "package.__version__"}
